name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:     
  build-push-ghcr:
    uses: ClubCedille/cedille-workflows/.github/workflows/build-push-ghcr.yaml@master
    with:
      container-name: ${{ github.event.repository.name }}
      pr-head-sha: ${{ github.event.pull_request.head.sha || '' }}
      pr-head-ref: ${{ github.event.pull_request.head.ref || '' }}
    secrets: inherit
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
